# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  DB_PASSWORD: cmxhd2pkZ2tz
  DB_USERNAME: aGFucw==
  JDBC_URL: amRiYzpteXNxbDovL3RlcnJhZm9ybS0yMDIyMDQxMjE0MjEyODI1MzYwMDAwMDAwNy5jY2c1MmNtb2w3aXEuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb206MzMwNi9sb2xqb2E/c2VydmVyVGltZXpvbmU9VVRD
kind: Secret
metadata:
  creationTimestamp: "2022-04-13T05:07:17Z"
  name: db-secret
  namespace: loljoa
  resourceVersion: "194634"
  uid: 32d685bb-dfca-4127-9cf9-df22de8d660e
type: Opaque
