apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  namespace: loljoa
spec:
  selector:
    service: chrome-driver
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: selenium
  namespace: loljoa
  labels:
    app: selenium
spec:
  selector:
    matchLabels:
      daemon: selenium
  template:
    metadata:
      labels:
        daemon: selenium
        service: chrome-driver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: selenium
        image: selenium/standalone-chrome:4.1.3-20220405
        volumeMounts:
          - mountPath: /dev/shm
            name: shmdir
        ports:
          - containerPort: 4444
      volumes:
      - name: shmdir
        emptyDir:
          medium: Memory
          sizeLimit: "512M"