apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-game-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: betting-game
  template:
    metadata:
      labels:
        app.kubernetes.io/name: betting-game
      annotations:
        prometheus.io: "True"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - loljoa
              topologyKey: "kubernetes.io/zone"
      containers:
      - name: betting-game-api
        image: loljoa/betting_game_api:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "400m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        env:
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: ACCESS_KEY_ID
              optional: false
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: SECRET_ACCESS_KEY
              optional: false 
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: JDBC_URL
              optional: false
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USERNAME
              optional: false 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
              optional: false
        - name: spring.profiles.active
          value: "prod"
        - name: S3_BUCKET_NAME
          value: "loljoa2-bucket"
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /api/betting/game/actuator/health/liveness
            port: 8080
          failureThreshold: 30
          periodSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
            path: /api/betting/game/actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: 8080
            path: /api/betting/game/actuator/health/readiness
          initialDelaySeconds: 10
          periodSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: betting-game-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: betting-game
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: betting-game-api
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: betting-game-api
 minReplicas: 3
 maxReplicas: 6
 targetCPUUtilizationPercentage: 30
