apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: main-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: main-ui
    spec:
      containers:
      - name: main-ui
        image: loljoa/front-main-ui:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "400m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: main-ui-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: main-ui
