apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-schedules-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: league-schedule
  template:
    metadata:
      annotations:
        prometheus.io: "True"
      labels:
        app.kubernetes.io/name: league-schedule
    spec:
      containers:
      - name: db-init
        image: loljoa/lck_schedule_apiserver:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "400m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        env:
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: ACCESS_KEY_ID
              optional: false
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: SECRET_ACCESS_KEY
              optional: false 
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: JDBC_URL
              optional: false
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USERNAME
              optional: false 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
              optional: false
        - name: spring.profiles.active
          value: "prod"
        - name: S3_BUCKET_NAME
          value: "loljoa2-bucket"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: league-schedule-api-svc
spec:
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: league-schedule
